name: Pull Request - Workflows Repository

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  conventional-commits:
    name: Conventional Commit Validation
    uses: ./.github/workflows/conventional-commit-v1.yml
    permissions:
      contents: read
      pull-requests: write 