name: Pull Request - Front-End Repositories

on:
  workflow_call:

jobs:
  conventional-commits:
    name: Conventional Commit Validation
    uses: ./.github/workflows/conventional-commit-v1.yml
    permissions:
      contents: read
      pull-requests: write 